Fix problems Starting Hive Server and Metastore Service in second git worktree Traceback (most recent call last):   File "/home/asherman/git/asf/Impala2/testdata/bin/wait-for-metastore.py", line 27, in <module>     from tests.util.thrift_util import create_transport   File "/home/asherman/git/asf/Impala2/tests/util/thrift_util.py", line 23, in <module>     import sasl   File "build/bdist.linux-x86_64/egg/sasl/__init__.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/sasl/saslwrapper.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_saslwrapper.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_saslwrapper.py", line 6, in __bootstrap__
ImportError: /home/asherman/git/asf/Impala2/toolchain/gcc-4.9.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/asherman/.cache/Python-Eggs/sasl-0.1.1-py2.7-linux-x86_64.egg-tmp/_saslwrapper.so)
ERROR in /home/asherman/git/asf/Impala2/testdata/bin/run-hive-server.sh at line 73: